# The vocabulary list contains pairs of English and Ukrainian phrases.
# Each entry in the list is a sublist with the following structure:
# [English_word, Ukrainian_word, English_sentence, Ukrainian_sentence]

vocab_list = [
    ["and", "та", "She likes coffee and tea.", "Вона любить каву та чай."],
    ["you", "ви", "I met you at the party.", "Я зустрів вас на вечірці."],
    ["they", "вони", "They went to the beach.", "Вони пішли на пляж."],
    ["or", "або", "Do you want tea or coffee?", "Ви хочете чай або каву?"],
    ["we", "ми", "We are going to the park.", "Ми йдемо в парк."],
    ["but", "але", "I like pizza, but I also enjoy pasta.", "Мені подобається піца, але я також люблю пасту."],
    ["she", "вона", "She is a doctor.", "Вона є лікарем."],
    ["so", "тому", "It was raining, so we stayed indoors.", "Ішов дощ, тому ми залишилися всередині."],
    ["there", "там", "I saw him there.", "Я бачив його там."],
    ["here", "тут, сюди", "Come here and sit down.", "Ходи сюди і сідай."],
    ["now", "зараз", "I'm busy right now.", "Зараз я зайнятий."],
    ["like", "подобатися", "I like ice cream.", "Мені подобається морозиво."],
    ["just", "просто", "I was just thinking about you.", "Я просто думав про тебе."],
    ["do", "робити", "What do you do for a living?", "Що ви робите для життя?"],
    ["can", "може", "Can you help me with this problem?", "Чи можете ви мені допомогти з цією проблемою?"],
    ["get", "отримати", "I need to get a new phone.", "Мені потрібно отримати новий телефон."],
    ["will", "буде", "It will rain tomorrow.", "Завтра буде дощ."],
    ["make", "робити", "She can make a delicious cake.", "Вона може зробити смачний торт."],
    ["see", "бачити", "I can't see without my glasses.", "Я не бачу без окулярів."],
    ["know", "знати", "Do you know the answer?", "Ти знаєш відповідь?"],
    ["come", "прийти", "Come to the party tonight.", "Прийди на вечірку сьогодні вечора."],
    ["think", "думати", "I think it's a good idea.", "Я думаю, це гарна ідея."],
    ["say", "говорити", "What did you say to him?", "Що ти сказав йому?"],
    ["see", "бачити", "I can see the mountains from here.", "Я бачу гори звідси."],
    ["take", "брати", "Can you take a photo for me?", "Чи можете ви зробити мені фото?"],
    ["help", "допомагати", "I need your help with this task.", "Мені потрібна твоя допомога з цим завданням."],
    ["use", "використовувати", "I use my laptop for work.", "Я використовую свій ноутбук для роботи."],
    ["find", "знаходити", "Can you help me find my keys?", "Чи можете ви мені допомогти знайти мої ключі?"],
    ["tell", "говорити, розповідати", "Can you tell me a story?", "Чи можете ви розповісти мені історію?"],
    ["ask", "питати", "Don't be afraid to ask questions.", "Не бійтеся питати питання."],
    ["work", "працювати", "I work from 9 to 5.", "Я працюю з 9 до 5."],
    ["seem", "здаватися", "It seems like a good idea.", "Здається, що це гарна ідея."],
    ["want", "хотіти", "I want to travel the world.", "Я хочу подорожувати по світу."],
    ["try", "спробувати", "I'll try my best to help you.", "Я спробую зробити все можливе, щоб вам допомогти."],
    ["need", "потребувати", "I need your advice.", "Мені потрібна ваша порада."],
    ["become", "стати", "I want to become a chef.", "Я хочу стати шеф-кухарем."],
    ["leave", "залишати", "Don't leave without saying goodbye.", "Не залишайтесь без прощання."],
    ["put", "класти", "Put the keys on the table.", "Покладіть ключі на стіл."],
    ["mean", "означати", "What does this word mean?", "Що означає це слово?"],
    ["keep", "тримати", "Can you keep a secret?", "Чи можете ви тримати секрет?"],
    ["start", "починати", "Let's start the meeting.", "Давайте почнемо нараду."],
    ["show", "показувати", "Can you show me the way?", "Чи можете ви мені показати дорогу?"],
    ["time", "час", "I don't have much time today.", "Сьогодні у мене не багато часу."],
    ["day", "день", "Tomorrow is a new day.", "Завтра новий день."],
    ["year", "рік", "I plan to travel next year.", "Я планую подорожувати наступного року."],
    ["way", "шлях", "Show me the way to the station.", "Покажіть мені шлях до вокзалу."],
    ["man", "чоловік", "The man is waiting for a bus.", "Чоловік чекає на автобус."],
    ["woman", "жінка", "She is a talented woman.", "Вона талановита жінка."],
    ["child", "дитина", "The child is playing in the park.", "Дитина грає в парку."],
    ["place", "місце", "Let's find a quiet place to talk.", "Знайдемо тихе місце для розмови."],
    ["thing", "річ", "I forgot to bring my things.", "Я забув взяти свої речі."],
    ["work", "робота", "I have a lot of work to do.", "У мене багато роботи."],
    ["job", "робота", "She got a new job.", "Вона отримала нову роботу."],
    ["house", "будинок", "I live in a small house.", "Я живу в невеликому будинку."],
    ["friend", "друг", "He is my best friend.", "Він мій найкращий друг."],
    ["family", "сім'я", "Family is important to me.", "Сім'я є важливою для мене."],
    ["life", "життя", "Enjoy every moment of life.", "Насолоджуйтеся кожним моментом життя."],
    ["school", "школа", "I go to school every day.", "Я ходжу до школи щодня."],
    ["book", "книга", "I love reading a good book.", "Я люблю читати хорошу книгу."],
    ["hand", "рука", "She extended her hand for a handshake.", "Вона простягла руку для рукостискання."],
    ["problem", "проблема", "We need to solve this problem.", "Нам потрібно вирішити цю проблему."],
    ["part", "частина", "I played a part in the school play.", "Я грав частину в шкільній виставі."],
    ["head", "голова", "I have a headache.", "У мене болить голова."],
    ["car", "автомобіль", "I drive a small car.", "Я керую маленьким автомобілем."],
    ["state", "штат", "California is a large state.", "Каліфорнія - це великий штат."],
    ["case", "випадок", "It's a unique case.", "Це унікальний випадок."],
    ["fact", "факт", "The fact is undeniable.", "Факт є неоспоримим."],
    ["example", "приклад", "Let me give you an example.", "Дозвольте мені подати вам приклад."],
    ["group", "група", "We are in the same group.", "Ми в одній групі."],
    ["change", "зміна", "Change is the only constant.", "Зміна - єдина постійна річ."],
    ["development", "розвиток", "Technological development is rapid.", "Технологічний розвиток є стрімким."],
    ["industry", "промисловість", "The city is known for its industry.", "Місто відоме своєю промисловістю."],
    ["system", "система", "A good education system is essential.", "Добра система освіти є важливою."],
    ["company", "компанія", "I work for a reputable company.", "Я працюю в поважній компанії."],
    ["number", "число", "The number of visitors is increasing.", "Число відвідувачів зростає."],
    ["government", "уряд", "The government is implementing new policies.", "Уряд впроваджує нові політики."],
    ["childhood", "дитинство", "Many memories are from my childhood.", "Багато спогадів з мого дитинства."],
    ["experience", "досвід", "Traveling provides valuable experience.", "Подорожі надають цінного досвіду."],
    ["community", "спільнота", "It's a close-knit community.", "Це згуртована спільнота."],
    ["area", "область", "This is a residential area.", "Це житлова область."],
    ["method", "метод", "Scientific methods are used in research.", "Наукові методи використовуються в дослідженнях."],
    ["point", "точка", "Let me explain my point of view.", "Дозвольте мені пояснити свою точку зору."],
    ["process", "процес", "Learning is a continuous process.", "Навчання - це постійний процес."],
    ["power", "сила", "Knowledge is a source of power.", "Знання - це джерело сили."],
    ["start", "початок", "The race starts at 9 o'clock.", "Перегони починаються о 9 годині."],
    ["horn", "сигнал", "The car horn is very loud.", "Сигнал автомобіля дуже гучний."],
    ["cave", "печера", "The cave is dark and mysterious.", "Печера темна і загадкова."],
    ["rightful", "правомірний", "It is rightful for you to be angry.", "Вам правомірно сердитися."],
    ["judge", "суддя", "The judge will decide the case.", "Суддя вирішить справу."],
    ["debonair", "вишуканий", "He is a very debonair gentleman.", "Він дуже вишуканий джентльмен."],
    ["subsequent", "наступний", "The subsequent events were very exciting.", "Наступні події були дуже захоплюючими."],
    ["crowd", "товпа", "The crowd was cheering for their team.", "Товпа вболівала за свою команду."],
    ["realize", "зрозуміти", "I finally realized what I had done.", "Я нарешті зрозумів, що я зробив."],
    ["quack", "крякати", "The ducks are quacking in the pond.", "Качки крякають у ставку."],
    ["silent", "тихий", "The room was silent.", "Кімната була тихою."],
    ["truck", "вантажівка", "The truck is carrying a load of hay.", "Вантажівка перевозить сіно."],
    ["giddy", "запаморочений", "The children were giddy with excitement.", "Діти були запаморочені від хвилювання."],
    ["thinkable", "можливий", "It is unthinkable that he would do such a thing.", "Немислимо, щоб він зробив таке."],
    ["mouth", "рот", "The baby is putting everything in its mouth.", "Дитина все кладе собі в рот."],
    ["opposite", "протилежний", "Black is the opposite of white.", "Чорний - протилежний білому."],
    ["breathe", "дихати", "I can't breathe!", "Я не можу дихати!"],
    ["awake", "прокинутися", "I woke up at 7 o'clock this morning.", "Я прокинувся о 7 годині ранку."],
    ["fragile", "крихкий", "The vase is very fragile.", "Ваза дуже тендітна."],
    ["farm", "ферма", "The farmer works on the farm.", "Фермер працює на фермі."],
    ["flagrant", "явний", "It was a flagrant foul.", "Це був явний фол."],
    ["vast", "величезний", "The ocean is vast.", "Океан величезний."],
    ["warn", "попередити", "I warned him not to go.", "Я попередив його, щоб він не йшов."],
    ["diligent", "старанний", "She is a very diligent student.", "Вона дуже старанна студентка."],
    ["scare", "злякати", "The loud noise scared the child.", "Гучний шум налякав дитину."],
    ["clip", "застібка", "The clip is holding the papers together.", "Застібка тримає папери разом."],
    ["cabbage", "капуста", "The cabbage is growing in the garden.", "Капуста росте в саду."],
    ["peck", "дзьобати", "The bird is pecking at the ground.", "Птах дзьобає землю."],
    ["graceful", "граціозний", "The ballerina moved gracefully across the stage.", "Балерина граціозно рухалася по сцені."],
    ["shape", "форма", "The shape of the cloud is changing.", "Форма хмари змінюється."],
    ["nest", "гніздо", "The birds are building a nest in the tree.", "Птахи будують гніздо на дереві."],
    ["obese", "ожирілий", "The man is obese and unhealthy.", "Чоловік ожирілий і нездоровий."],
    ["geese", "гуси", "The geese are flying south for the winter.", "Гуси летять на південь на зиму."],
    ["cross", "перетинати", "The road crosses the river.", "Дорога перетинає річку."],
    ["coast", "узбережжя", "We spent our vacation on the coast.", "Ми провели відпустку на узбережжі."],
    ["wise", "мудрий", "The old man is wise and knowledgeable.", "Старий мудрий і розумний."],
    ["flap", "махати", "The bird flapped its wings and flew away.", "Птах махнув крилами і полетів."],
    ["tall", "високий", "The giraffe is the tallest animal in the world.", "Жирафа - найвища тварина у світі."],
    ["oafish", "невмілий", "The player was oafish and clumsy.", "Гравець був невмілим і незграбним."],
    ["bath", "ванна", "The baby is taking a bath.", "Дитина приймає ванну."],
    ["redundant", "зайвий", "The information is redundant and unnecessary.", "Інформація зайва і непотрібна."],
    ["position", "позиція", "The player is in a good position to score.", "Гравець займає гарну позицію для взяття воріт."],
    ["picayune", "нікчемний", "The manager is picayune and petty.", "Менеджер дріб'язковий і дріб'язковий."],
    ["pedal", "педаль", "The cyclist pressed on the pedal and accelerated.", "Велосипедист натиснув на педаль і прискорився."],
    ["army", "армія", "The army is defending the country.", "Армія захищає країну."],
    ["strange", "дивний", "The man is acting strange.", "Чоловік поводиться дивно."],
    ["dress", "сукня", "The woman is wearing a beautiful dress.", "Жінка одягнена в гарну сукню."],
    ["table", "стіл", "The family is eating dinner at the table.", "Сім'я вечеряє за столом."],
    ["drum", "барабан", "The drummer hit the drum with his sticks.", "Барабанщик ударив по барабану паличками."],
    ["lace", "мереживо", "The dress is trimmed with lace.", "Сукня прикрашена мереживом."],
    ["icicle", "бурулька", "The icicles are hanging from the roof.", "Бурульки звисають з даху."],
    ["snow", "сніг", "The snow is falling from the sky.", "Сніг падає з неба."],
    ["question", "питання", "I have a question about the assignment.", "У мене є питання щодо завдання."],
    ["cheese", "сир", "The cheese is made from milk.", "Сир виготовляють з молока."],
    ["cheer", "радіти", "The crowd is cheering for their team.", "Товпа вболіває за свою команду."],
    ["monkey", "мавпа", "The monkey is swinging from the trees.", "Мавпа гойдається на деревах."],
    ["learned", "вивчив", "I learned a new word today.", "Я вивчив нове слово сьогодні."],
    ["shiver", "тремтіти", "I am shivering because I am cold.", "Я тремчу, тому що мені холодно."],
    ["reply", "відповідати", "Please reply to my email.", "Будь ласка, відповідайте на мій електронний лист."],
    ["peaceful", "мирний", "The world is a peaceful place.", "Світ - мирне місце."],
    ["dirty", "брудний", "The child is dirty from playing in the mud.", "Дитина брудна від гри в грязі."],
    ["chilly", "прохолодний", "It is chilly outside today.", "Сьогодні на вулиці прохолодно."],
    ["gentle", "ніжний", "The gentle breeze is blowing through the trees.", "Ніжний вітерець дме через дерева."],
    ["neighborly", "сусідський", "The neighbors are very neighborly.", "Сусіди дуже сусідські."],
    ["waves", "хвилі", "The waves are crashing on the shore.", "Хвилі б'ються об берег."],
    ["tan", "засмага", "The man has a tan from spending time at the beach.", "У чоловіка засмага від проведення часу на пляжі."],
    ["dogs", "собаки", "The dogs are barking.", "Собаки гавкають."],
    ["thundering", "гримлячий", "The thunder is thundering.", "Грім гримить."],
    ["obtain", "отримати", "I obtained a new job.", "Я отримав нову роботу."],
    ["undress", "роздягатися", "She undressed and got into bed.", "Вона роздягнулася і лягла в ліжко."],
    ["saw", "пиляв", "The man saw the tree down.", "Чоловік спиляв дерево."],
    ["onerous", "важкий", "The task is too onerous.", "Завдання надто важке."],
    ["slap", "ляпас", "The man slapped the child.", "Чоловік дав ляпас дитині."],
    ["relieved", "полегшений", "I am relieved that the exam is over.", "Я полегшений, що іспит закінчився."],
    ["sand", "пісок", "The beach is full of sand.", "Пляж повний піску."],
    ["can", "можу", "I can speak three languages.", "Я можу говорити трьома мовами."],
    ["devilish", "диявольський", "The child has a devilish grin.", "У дитини диявольська усмішка."],
    ["calendar", "календар", "I have a calendar on my wall.", "У мене є календар на стіні."],
    ["title", "титул", "The book has an interesting title.", "У книги цікава назва."],
    ["protest", "протестувати", "The people are protesting against the government.", "Люди протестують проти уряду."],
    ["tacky", "безглуздий", "The shirt is tacky and ugly.", "Сорочка безглузда і потворна."],
    ["flight", "політ", "The plane is taking off on its flight.", "Літак злітає у рейс."],
    ["encourage", "заохочувати", "I encouraged him to follow his dreams.", "Я заохотив його слідувати своїм мріям."],
    ["breezy", "вітряний", "It is a breezy day.", "Сьогодні вітряний день."],
    ["prose", "проза", "The novel is written in prose.", "Роман написаний прозою."],
    ["threatening", "загрозливий", "The man is threatening to leave.", "Чоловік загрожує піти."],
    ["disapprove", "не схвалювати", "I disapprove of your behavior.", "Я не схвалюю вашу поведінку."],
    ["battle", "битва", "The two armies fought a fierce battle.", "Дві армії вели запеклу битву."],
    ["nice", "гарний", "The weather is nice today.", "Сьогодні гарна погода."],
    ["fierce", "лютий", "The lion is a fierce predator.", "Лев - лютий хижак."],
    ["flesh", "м'ясо", "The meat is cooked to perfection.", "М'ясо приготовлено ідеально."],
    ["memorize", "запам'ятовувати", "I need to memorize this poem for my exam.", "Мені потрібно запам'ятати цей вірш до іспиту."],
    ["practice", "практикувати", "You need to practice your piano skills regularly.", "Вам потрібно регулярно практикувати свої навички гри на піаніно."],
    ["division", "поділ", "The company is undergoing a major division.", "Компанія переживає серйозний поділ."],
    ["harmonious", "гармонійний", "The orchestra played harmoniously.", "Оркестр грав гармонійно."],
    ["nondescript", "невиразний", "The car is a nondescript brown color.", "Автомобіль невиразного коричневого кольору."],
    ["parsimonious", "ощадливий", "The old man is very parsimonious with his money.", "Старий дуже ощадливий з грошима."],
    ["toes", "пальці ніг", "The child is wiggling their toes in the sand.", "Дитина ворушить пальцями ніг у піску."],
    ["flaky", "лускатий", "The pastry is flaky and delicious.", "Випічка луската і смачна."],
    ["lackadaisical", "байдужий", "The employee was lackadaisical about their work.", "Працівник був байдужим до своєї роботи."],
    ["story", "історія", "The old woman told me a story about her childhood.", "Стара розповіла мені історію про своє дитинство."],
    ["nippy", "кусючий", "The wind is nippy today.", "Сьогодні вітряно."],
    ["committee", "комітет", "The committee is responsible for making decisions about the new policy.", "Комітет відповідає за прийняття рішень щодо нової політики."],
    ["eminent", "видатний", "The scientist is an eminent expert in her field.", "Вчений - видатний експерт у своїй галузі."],
    ["staking", "забиваючи кілки", "The campers are staking their tents.", "Туристи забивають кілки для своїх наметів."],
    ["alarm", "тривога", "The fire alarm is ringing.", "Пожежна сигналізація дзвонить."],
    ["offbeat", "незвичайний", "The movie has an offbeat sense of humor.", "У фільму незвичайне почуття гумору."],
    ["secretary", "секретар", "The secretary is typing a letter.", "Секретар набирає листа."],
    ["bite", "кусати", "The dog bit the postman.", "Собака вкусила листоношу."],
    ["possible", "можливий", "It is possible that the train will be late.", "Можливо, що поїзд запізниться."],
    ["appreciate", "оцінювати", "I appreciate your help.", "Я ціную вашу допомогу."],
    ["desire", "бажання", "My greatest desire is to travel the world.", "Моє найголовніше бажання - подорожувати світом."],
    ["useless", "безглуздий", "The instruction manual is useless.", "Інструкція безглузда."],
    ["bruise", "синець", "The child has a bruise on their arm.", "У дитини синець на руці."],
    ["shelter", "притулок", "The homeless man is looking for shelter.", "Бездомний шукає притулку."],
    ["toothsome", "апетитний", "The cake is toothsome and tempting.", "Торт апетитний і спокусливий."],
    ["bad", "поганий", "The situation is bad.", "Ситуація погана."],
    ["unequaled", "неперевершений", "Her beauty is unequaled.", "Її краса неперевершена."],
    ["deranged", "божевільний", "The deranged man was screaming at the top of his lungs.", "Божевільний чоловік кричав з усієї душі."],
    ["knit", "в'язати", "My grandmother knits me a sweater every year.", "Моя бабуся в'яже мені светр щороку."],
    ["curtain", "завіса", "The curtain was drawn across the window.", "Завіса була засунута через вікно."],
    ["hilarious", "дуже смішний", "The comedian told a hilarious joke that made everyone laugh.", "Комедіант розповів дуже смішне жарт, яке всіх розсмішило."],
    ["colossal", "колосальний", "The statue is colossal in size.", "Статуя колосальна за розміром."],
    ["encouraging", "заохочуючий", "The teacher's encouraging words helped me to believe in myself.", "Заохочуючі слова вчительки допомогли мені повірити в себе."],
    ["concern", "занепокоєння", "I have a concern about your behavior.", "Я стурбований вашою поведінкою."],
    ["uncovered", "неприкритий", "The archaeologist uncovered an ancient tomb.", "Археолог виявив давню гробницю."],
    ["fact", "факт", "It is a fact that the earth is round.", "Це факт, що земля кругла."],
    ["righteous", "праведний", "The righteous man always did the right thing.", "Праведний чоловік завжди робив правильно."],
    ["seat", "місце", "Please take a seat.", "Будь ласка, сядьте."],
    ["many", "багато", "There are many people in the world.", "У світі багато людей."],
    ["nostalgic", "ностальгійний", "The old song made me feel nostalgic.", "Стара пісня викликала у мене ностальгію."],
    ["clumsy", "невмілий", "The clumsy child knocked over the vase.", "Невміла дитина перекинула вазу."],
    ["decay", "розпад", "The old building is in a state of decay.", "Стара будівля перебуває в стані розпаду."],
    ["smoggy", "задимлений", "The city is very smoggy today.", "Місто дуже задимлене сьогодні."],
    ["scrawny", "худий і слабкий", "The scrawny cat was begging for food.", "Худа і слабка кішка просила їжі."],
    ["immense", "величезний", "The ocean is immense and vast.", "Океан величезний і безмежний."],
    ["apologize", "вибачатися", "I apologize for being late.", "Я вибачаюсь за запізнення."],
    ["aggressive", "агресивний", "The aggressive dog was barking at the mailman.", "Агресивний собака гавкав на листоношу."],
    ["rub", "терти", "I rubbed my eyes because they were tired.", "Я протер очі, бо вони були втомлені."],
    ["statue", "статуя", "The statue of liberty is a famous landmark in New York City.", "Статуя Свободи - відома пам'ятка в Нью-Йорку."],
    ["quince", "айва", "The quince is a type of fruit that is used to make jelly.", "Айва - це фрукт, який використовується для приготування желе."],
    ["house", "будинок", "The house is where you live.", "Будинок - це місце, де ви живете."],
    ["advise", "радити", "The doctor advised me to get more rest.", "Лікар порадив мені більше відпочивати."],
    ["suggestion", "пропозиція", "I have a suggestion for how to improve the project.", "У мене є пропозиція щодо поліпшення проекту."],
    ["mass", "маса", "The mass of the object is a measure of its quantity of matter.", "Маса об'єкта - це міра його кількості речовини."],
    ["ray", "промінь", "The sun's rays were shining through the window.", "Промені сонця світили через вікно."],
    ["dare", "важити", "I dare you to jump into the pool.", "Я тебе змушую стрибнути в басейн."],
    ["quickest", "найшвидший", "The cheetah is the quickest land animal.", "Гепард - найшвидша наземна тварина."],
    ["lush", "пишний", "The garden was lush and green.", "Сад був пишним і зеленим."],
    ["bashful", "сором'язливий", "The bashful child was shy and timid.", "Сором'язлива дитина була сором'язливою і боязкою."],
    ["company", "компанія", "The company is expanding into new markets.", "Компанія розширюється на нові ринки."],
    ["heal", "загоювати", "The doctor helped to heal the patient's wounds.", "Лікар допоміг загоїти рани пацієнта."],
    ["gabby", "балакучий", "The gabby child never stopped talking.", "Балакуча дитина ніколи не замовкала."],
    ["pen", "ручка", "The writer used a pen to write her novel.", "Письменник використовував ручку, щоб написати свій роман."],
    ["numerous", "численний", "There are numerous stars in the sky.", "На небі є численні зірки."],
    ["grape", "виноград", "The grapes are sweet and juicy.", "Виноград солодкий і соковитий."],
    ["small", "маленький", "The mouse is a small animal.", "Миша - маленька тварина."],
    ["joke", "жарт", "The comedian told a funny joke that made everyone laugh.", "Комедіант розповів смішний жарт, який всіх розсмішило."],
    ["tow", "буксирувати", "The tow truck towed the car to the repair shop.", "Евакуатор відтягнув машину в ремонтну майстерню."],
    ["zoom", "збільшувати", "The photographer zoomed in on the bird's eye.", "Фотограф збільшив очі птаха."],
    ["brick", "цегла", "The brick house is very strong.", "Цегляний будинок дуже міцний."],
    ["zoo", "зоопарк", "The zoo is home to many different animals.", "У зоопарку мешкає багато різних тварин."],
    ["obedient", "слухняний", "The obedient child always followed their parents' instructions.", "Слухняна дитина завжди виконувала вказівки батьків."],
    ["mundane", "буденний", "The mundane tasks of everyday life can be boring.", "Буденні справи повсякденного життя можуть бути нудними."],
    ["macabre", "жахливий", "The macabre story made the listeners feel uneasy.", "Жахлива історія викликала у слухачів неприємне відчуття."],
    ["space", "простір", "The vastness of space is awe-inspiring.", "Безмежність простору надихає."],
    ["impress", "вражати", "The magician's tricks impressed the audience.", "Фокуси фокусника вразили публіку."],
    ["cooing", "воркувати", "The doves were cooing softly in the trees.", "Голуби тихо воркували на деревах."],
    ["horrible", "жахливий", "The horrible accident left many people injured.", "Жахлива аварія залишила багато людей пораненими."],
    ["wander", "блукати", "The lost child wandered through the forest.", "Загублена дитина блукала по лісі."],
    ["pocket", "кишеня", "The man put his phone in his pocket.", "Чоловік поклав телефон у кишеню."],
    ["distinct", "виразний", "The two colors are very distinct.", "Два кольори дуже виразні."],
    ["sip", "попивати", "I sipped my coffee slowly.", "Я попивав свою каву повільно."],
    ["imagine", "уявляти", "I can imagine what it would be like to live on Mars.", "Я можу уявити, як було б жити на Марсі."],
    ["develop", "розвиватися", "The company is developing new software.", "Компанія розробляє нове програмне забезпечення."],
    ["aboard", "на борту", "The passengers boarded the plane.", "Пасажири сіли на літак."],
    ["cake", "торт", "The cake is my favorite dessert.", "Торт - мій улюблений десерт."],
    ["premium", "преміальний", "The premium coffee is made with the finest beans.", "Преміальна кава виготовлена ​​з найкращих зерен."],
    ["car", "автомобіль", "The car is a popular mode of transportation.", "Автомобіль - популярний вид транспорту."],
    ["sticky", "липкий", "The honey is very sticky.", "Мед дуже липкий."],
    ["supreme", "найвищий", "The supreme court is the highest court in the land.", "Верховний суд - найвищий суд у країні."],
    ["grey", "сірий", "The sky is grey.", "Небо сіре."],
    ["explain", "пояснювати", "The teacher explained the concept to the students.", "Вчитель пояснив концепцію учням."],
    ["boiling", "кипіння", "The water is boiling in the pot.", "Вода кипить у каструлі."],
    ["shave", "голитися", "The man shaved his beard.", "Чоловік зголив бороду."],
    ["airplane", "літак", "The airplane flew high in the sky.", "Літак високо летів у небі."],
    ["magical", "чарівний", "The magician performed a magical trick.", "Чарівник виконав чарівний фокус."],
    ["cats", "коти", "Cats are popular pets.", "Коти - популярні домашні тварини."],
    ["pump", "насос", "The pump is used to inflate the tires.", "Насос використовується для накачування шин."],
    ["peep", "підглядати", "The child peeped through the keyhole.", "Дитина підглядала через замкову щілину."],
    ["amused", "забавлений", "The audience was amused by the comedian's jokes.", "Публіка була забавлена жартами коміка."],
    ["hesitant", "вагаючийся", "The hesitant student wasn't sure how to answer the question.", "Вагаючийся учень не знав, як відповісти на запитання."],
    ["handy", "зручний", "The handy tool helped me fix the problem.", "Зручний інструмент допоміг мені вирішити проблему."],
    ["noisy", "шумний", "The noisy crowd made it difficult to hear.", "Шумливий натовп ускладнював чутність."],
    ["scissors", "ножиці", "The scissors are used to cut paper.", "Ножиці використовуються для різання паперу."],
    ["song", "пісня", "The singer sang a beautiful song.", "Співачка заспівала гарну пісню."],
    ["truthful", "правдивий", "The truthful child always told the truth.", "Правдива дитина завжди говорила правду."],
    ["add", "додавати", "Please add two more cups of flour.", "Будь ласка, додайте ще дві чашки борошна."],
    ["keen", "гострий", "The keen knife cut the meat easily.", "Гострий ніж легко різав м'ясо."],
    ["punch", "удар", "The boxer threw a powerful punch.", "Боксер завдав потужного удару."],
    ["complex", "складний", "The complex problem required a lot of thought.", "Для вирішення складної проблеми потрібно було багато думати."],
    ["mist", "туман", "The mist shrouded the forest in mystery.", "Туман оповив ліс таємницею."],
    ["small", "маленький", "The small child held my hand.", "Маленька дитина тримала мене за руку."],
    ["irate", "розлючений", "The irate customer complained to the manager.", "Розлючений клієнт поскаржився менеджеру."],
    ["rabbits", "кролики", "The rabbits hopped through the field.", "Кролики стрибали по полю."],
    ["wealthy", "багатий", "The wealthy family lived in a mansion.", "Багата сім'я жила в особняку."],
    ["scarce", "рідкісний", "Water is scarce in the desert.", "Вода рідкісна в пустелі."],
    ["cynical", "цинічний", "The cynical critic didn't have a good word to say about anyone.", "Цинічний критик не мав доброго слова ні про кого."],
    ["deer", "олень", "The deer grazed in the meadow.", "Олень пасся на лузі."],
    ["death", "смерть", "Death is a natural part of life.", "Смерть - природна частина життя."],
    ["meddle", "втручатися", "Please don't meddle in my affairs.", "Будь ласка, не втручайся в мої справи."],
    ["appliance", "побутовий прилад", "The kitchen is full of appliances.", "Кухня повна побутових приладів."],
    ["pleasure", "задоволення", "I take great pleasure in reading.", "Я отримую величезне задоволення від читання."],
    ["drag", "тягати", "The dog dragged the toy across the floor.", "Собака тягала іграшку по підлозі."],
    ["found", "знайти", "I found my lost keys under the couch.", "Я знайшов свої загублені ключі під диваном."],
    ["victorious", "переможний", "The victorious team celebrated their win.", "Переможна команда святкувала свою перемогу."],
    ["workable", "здійсненний", "The plan is workable if we make some adjustments.", "План здійсненний, якщо ми внесемо деякі корегування."],
    ["ignore", "ігнорувати", "I tried to ignore the noise from the street.", "Я намагався ігнорувати шум з вулиці."],
    ["soothe", "заспокоювати", "The mother soothed her crying baby.", "Мати заспокоїла свою плачучу дитину."],
    ["breath", "дихання", "I took a deep breath to calm myself down.", "Я зробив глибокий вдих, щоб заспокоїтися."],
    ["animated", "живий, жвавий", "The animated film was enjoyed by people of all ages.", "Мультиплікаційний фільм сподобався людям усіх віків."],
    ["obey", "слухатися", "The children obeyed their parents' instructions.", "Діти виконували вказівки батьків."],
    ["expand", "розширювати", "The company is expanding its operations into new markets.", "Компанія розширює свою діяльність на нові ринки."],
    ["boring", "нудний", "The lecture was so boring that I fell asleep.", "Лекція була настільки нудною, що я заснув."],
    ["bone", "кістка", "The dog chewed on a bone.", "Собака гризла кістку."],
    ["lunchroom", "їдальня", "The students ate their lunch in the lunchroom.", "Учні їли обід у їдальні."],
    ["reason", "причина", "The reason for the delay was the heavy traffic.", "Причиною затримки був гучний рух."],
    ["apathetic", "байдужий", "The apathetic student didn't care about school.", "Байдужому студентові було байдуже до школи."],
    ["leg", "нога", "The man broke his leg in a car accident.", "Чоловік зламав ногу в автокатастрофі."],
    ["interest", "інтерес", "The teacher sparked the students' interest in history.", "Вчитель пробудив у дітей інтерес до історії."],
    ["grouchy", "буркотливий", "The old man was grouchy all day.", "Старий весь день був буркотливим."],
    ["tree", "дерево", "The tree stood tall and proud in the forest.", "Дерево стояло високе і горде в лісі."],
    ["heady", "п'янкий", "The smell of the flowers was heady and intoxicating.", "Запах квітів був п'янким і дурманливим."],
    ["daughter", "дочка", "My daughter is the light of my life.", "Моя дочка - світло мого життя."],
    ["smash", "розбивати", "The car smashed into the tree.", "Автомобіль врізався в дерево."],
    ["teeny", "маленький", "The baby was teeny tiny.", "Дитина була маленькою."],
    ["suspect", "підозрювати", "I suspect that he is lying to me.", "Я підозрюю, що він мені бреше."],
    ["incredible", "неймовірний", "The view from the top of the mountain was incredible.", "Вид з вершини гори був неймовірним."],
    ["driving", "водіння", "I love the feeling of driving with the windows down.", "Я люблю відчуття їзди з відкритими вікнами."],
    ["comfortable", "зручний", "The new couch is very comfortable.", "Новий диван дуже зручний."],
    ["first", "перший", "The first day of school is always exciting.", "Перший день навчання завжди хвилюючий."],
    ["groovy", "класний", "The music was groovy and upbeat.", "Музика була класною та жвавою."],
    ["face", "обличчя", "The man had a long, thin face.", "У чоловіка було довге, тонке обличчя."],
    ["ancient", "давній", "The ancient ruins stood as a testament to a lost civilization.", "Давні руїни стояли як свідчення втраченої цивілізації."],
    ["arrive", "прибувати", "The train arrived at the station on time.", "Потяг прибув на станцію вчасно."],
    ["organic", "органічний", "I prefer to eat organic food.", "Я віддаю перевагу органічній їжі."],
    ["multiply", "множити", "Two multiplied by three equals six.", "Два помножені на три дорівнюють шести."],
    ["brash", "зухвалий", "The brash young man had no fear of speaking his mind.", "Зухвалий молодий чоловік не боявся говорити те, що думає."],
    ["knowing", "знаючий", "She had a knowing look in her eyes.", "У неї був розуміючий погляд в очах."],
    ["join", "приєднуватися", "I would like to join your club.", "Я хотів би приєднатися до вашого клубу."],
    ["jumbled", "змішаний", "The papers were all jumbled up.", "Папери були всі змішані."],
    ["cent", "цент", "The cost of the candy bar was only ten cents.", "Вартість цукерки становила лише десять центів."],
    ["teeth", "зуби", "The child showed its teeth in a wide grin.", "Дитина показала зуби в широкій усмішці."],
    ["heartbreaking", "душераздираючий", "The movie was heartbreaking.", "Фільм був душераздираючим."],
    ["third", "третій", "He was the third in line.", "Він був третім у черзі."],
    ["permit", "дозволяти", "Do I need a permit to park here?", "Мені потрібен дозвіл, щоб тут паркуватися?"],
    ["dinner", "обід", "What are we having for dinner?", "Що ми будемо їсти на обід?"],
    ["nervous", "нервовий", "She was nervous before her first day of school.", "Вона була нервовою перед першим днем навчання в школі."],
    ["knot", "вузол", "He tied the rope in a knot.", "Він зав'язав мотузку вузлом."],
    ["instinctive", "інстинктивний", "The dog instinctively knew that the stranger was dangerous.", "Собака інстинктивно знала, що незнайомець був небезпечним."],
    ["scream", "кричати", "The woman screamed in fear.", "Жінка закричала від страху."],
    ["known", "відомий", "She is a known actress.", "Вона відома актриса."],
    ["gaping", "зіваючий", "The child had a gaping mouth.", "У дитини був відкритий рот."],
    ["ceaseless", "безперервний", "The rain fell ceaselessly.", "Дощ лив безперервно."],
    ["garrulous", "балакучий", "The old woman was very garrulous.", "Стара жінка була дуже балакучою."],
    ["plants", "рослини", "The garden was full of plants.", "Сад був повний рослин."],
    ["zonked", "виснажений", "I was zonked after working all day.", "Я був виснажений після цілого дня роботи."],
    ["sister", "сестра", "She is my sister.", "Вона моя сестра."],
    ["best", "найкращий", "He is the best friend I could ask for.", "Він найкращий друг, якого я тільки міг побажати."],
    ["shop", "магазин", "I'm going to the shop to buy some groceries.", "Я йду в магазин, щоб купити продукти."],
    ["enchanting", "чарівний", "The scenery was enchanting.", "Краєвид був чарівним."],
    ["likeable", "симпатичний", "She is a very likeable person.", "Вона дуже симпатична людина."],
    ["hateful", "ненависний", "He said some very hateful things.", "Він сказав кілька дуже ненависних речей."],
    ["silly", "дурний", "That was a silly thing to do.", "Це було дурною річчю робити."],
    ["fire", "вогонь", "The fire was crackling in the fireplace.", "Вогонь потріскував у каміні."],
    ["brake", "гальма", "The driver slammed on the brakes.", "Водій різко заблокував гальма."],
    ["seemly", "пристойний", "It is not seemly to behave that way.", "Непристойно поводитися таким чином."],
    ["loaf", "буханець", "I bought a loaf of bread.", "Я купив буханець хліба."],
    ["tacit", "мовчазний", "There was a tacit understanding between them.", "Між ними існувало мовчазне порозуміння."],
    ["excite", "збуджувати", "The news excited me.", "Новина мене збудила."],
    ["average", "середній", "I got an average grade on the test.", "Я отримав середню оцінку на іспиті."],
    ["miss", "скучати", "I miss you.", "Я сумую за тобою."],
    ["astonishing", "дивовижний", "The view was astonishing.", "Вид був дивовижним."],
    ["representative", "представник", "She is a representative of the company.", "Вона є представником компанії."],
    ["pail", "відро", "I used the pail to collect water from the river.", "Я використав відро, щоб набрати води з річки."],
    ["explode", "вибухати", "The bomb exploded with a loud bang.", "Бомба вибухнула з гучним вибухом."],
    ["wire", "дріт", "The electrician carefully connected the wires.", "Електрик обережно з'єднав дроти."],
    ["vagabond", "волоцюга", "The vagabond wandered from town to town.", "Волоцюга блукав від міста до міста."],
    ["ill-informed", "необізнаний", "The speaker was ill-informed about the topic.", "Доповідач був необізнаний з теми."],
    ["steam", "пара", "The steam from the tea kettle rose into the air.", "Пара з чайника піднялася в повітря."],
    ["aback", "здивований", "I was taken aback by her unexpected question.", "Мене здивувало її несподіване запитання."],
    ["classy", "стильний", "She always dresses in a classy and elegant way.", "Вона завжди одягається стильно та елегантно."],
    ["standing", "стоячи", "The tall man was standing head and shoulders above the crowd.", "Високий чоловік стояв на голову вище за натовп."],
    ["defective", "дефектний", "The defective product was returned to the store.", "Дефектний товар був повернутий в магазин."],
    ["idea", "ідея", "He had a brilliant idea for a new business.", "У нього була блискуча ідея для нового бізнесу."],
    ["married", "одружений", "He has been married to his wife for ten years.", "Він одружений зі своєю дружиною десять років."],
    ["hunt", "полювання", "The hunters went into the forest to hunt deer.", "Мисливці пішли в ліс полювати на оленів."],
    ["loose", "вільний", "The button is loose on my shirt.", "Ґудзик на моїй сорочці вільний."],
    ["ugliest", "найпотворніший", "That is the ugliest dress I have ever seen.", "Це найпотворніша сукня, яку я коли-небудь бачив."],
    ["two", "два", "There are two apples on the table.", "На столі є два яблука."],
    ["haunt", "переслідувати", "The ghost is said to haunt the old castle.", "Кажуть, що привид переслідує старий замок."],
    ["bored", "занудьгувати", "I am so bored. There is nothing to do.", "Мені так нудно. Нічого не можна робити."],
    ["scorch", "палити", "The sun scorched the earth.", "Сонце спалило землю."],
    ["territory", "територія", "This is our territory.", "Це наша територія."],
    ["pencil", "олівець", "I need a pencil to write my essay.", "Мені потрібен олівець, щоб написати своє есе."],
    ["view", "вид", "The view from the top of the mountain is amazing.", "Вид з вершини гори вражає."],
    ["blood", "кров", "The blood flowed freely from the wound.", "Кров текла з рани потоком."],
    ["powerful", "потужний", "He is a powerful man.", "Він потужна людина."],
    ["royal", "королівський", "The royal family lived in the palace.", "Королівська сім'я жила в палаці."],
    ["proud", "гордий", "He is proud of his accomplishments.", "Він пишається своїми досягненнями."],
    ["abashed", "збентежений", "She was abashed by the compliment.", "Її збентежив комплімент."],
    ["bikes", "велосипеди", "We went for a bike ride in the park.", "Ми покаталися на велосипедах у парку."],
    ["psychotic", "психотичний", "The psychotic man attacked the stranger.", "Психотичний чоловік напав на незнайомця."],
    ["squash", "гарбуз", "I made a delicious squash soup.", "Я приготував смачний суп з гарбуза."],
    ["delicious", "смачний", "This cake is delicious.", "Цей торт смачний."],
    ["goofy", "безглуздий", "He is such a goofy guy.", "Він такий безглуздий хлопець."],
    ["worry", "турбуватися", "Don't worry, everything will be alright.", "Не турбуйся, все буде добре."],
    ["tight", "тугий", "The shirt was too tight for me.", "Сорочка була мені занадто тугою."],
    ["nonchalant", "байдужий", "He was nonchalant about the whole situation.", "Він був байдужий до всієї ситуації."],
    ["rainy", "дощовий", "It was a rainy day.", "Був дощовий день."],
    ["panicky", "панічний", "She was panicky about the exam.", "Вона була палкою перед іспитом."],
    ["brief", "короткий", "The meeting was brief and to the point.", "Зустріч була короткою і по суті."],
    ["flow", "текти", "The river flowed through the valley.", "Річка текла через долину."],
    ["quicksand", "пливун", "The car was stuck in the quicksand.", "Машина застрягла в пливуні."],
    ["delight", "задоволення", "She took delight in watching the children play.", "Їй було приємно спостерігати за грою дітей."],
    ["bolt", "блискавка", "A bolt of lightning struck the tree.", "Блискавка вдарила в дерево."],
    ["zephyr", "легкий вітерець", "A gentle zephyr blew through the trees.", "Легкий зефір пробіг між деревами."],
    ["applaud", "оплескувати", "The audience applauded the performance.", "Публіка аплодувала виставі."],
    ["donkey", "осел", "The donkey carried the load with patience.", "Осел терпляче ніс ношу."],
    ["reflect", "відображати", "The mirror reflected her image.", "Дзеркало відображало її образ."],
    ["weary", "втомлений", "She was weary after the long journey.", "Вона була втомою після довгої подорожі."],
    ["treatment", "лікування", "The patient received treatment for their illness.", "Пацієнт отримав лікування від своєї хвороби."],
    ["elfin", "ельфський", "She had an elfin face with delicate features.", "У неї було ельфське обличчя з тонкими рисами."],
    ["eight", "вісім", "There were eight people at the table.", "За столом було вісім людей."],
    ["lopsided", "перекошений", "The picture frame was lopsided.", "Рамка для картини була перекошеною."],
    ["sore", "хворий", "Her throat was sore from too much talking.", "У неї боліло горло від надмірної розмови."],
    ["pastoral", "пасторальний", "The scene was idyllic and pastoral.", "Сцена була ідилічною та пасторальною."],
    ["cellar", "підвал", "The wine was stored in the cellar.", "Вино зберігалося в підвалі."],
    ["kiss", "поцілунок", "He gave her a kiss on the cheek.", "Він поцілував її в щоку."],
    ["meaty", "м'ясний", "The stew was hearty and meaty.", "Рагу був ситним і м'ясним."],
    ["discovery", "відкриття", "The discovery of the new drug was a major breakthrough.", "Відкриття нового препарату стало значним проривом."],
    ["birth", "народження", "The birth of their child was a joyous occasion.", "Народження їхньої дитини було радісною подією."],
    ["bounce", "скакати", "The ball bounced high in the air.", "М'яч високо підскочив у повітрі."],
    ["nimble", "спритний", "The acrobat was nimble and agile.", "Акробат був спритним та рухливим."],
    ["tug", "смикати", "He tugged at the rope to pull the boat closer.", "Він смикнув за мотузку, щоб підтягнути човен ближче."],
    ["fretful", "неспокійний", "The baby was fretful and wouldn't settle down.", "Дитина була неспокійною і не могла заспокоїтися."],
    ["aberrant", "аномальний", "The aberrant behavior raised concerns.", "Аномальна поведінка викликала занепокоєння."],
    ["rude", "грубий", "The rude customer complained about the service.", "Грубий клієнт скаржився на обслуговування."],
    ["roll", "катати", "The ball rolled down the hill.", "М'яч скотився з пагорба."],
    ["earthquake", "землетрус", "The earthquake caused widespread damage.", "Землетрус завдав величезних збитків."],
    ["uncle", "дядько", "My uncle visited from out of town.", "Мій дядько приїхав з іншого міста."],
    ["design", "дизайн", "The design of the building was innovative.", "Дизайн будівлі був інноваційним."],
    ["glib", "балакучий", "The glib salesman made exaggerated promises.", "Балакучий продавець робив перебільшені обіцянки."],
    ["act", "діяти", "You need to act quickly to resolve the issue.", "Вам потрібно діяти швидко, щоб вирішити проблему."],
    ["sneaky", "підступний", "The sneaky thief stole the purse without being noticed.", "Підступний злодій вкрав сумку непоміченим."],
    ["elastic", "еластичний", "The elastic band stretched without breaking.", "Еластична стрічка розтягувалася, не рвучись."],
    ["healthy", "здоровий", "Eating a balanced diet is important for staying healthy.", "Здорове харчування важливе для збереження здоров'я."],
    ["fairy", "фея", "The fairy tale told the story of a kind fairy.", "Казка розповідала історію доброї феї."],
    ["activity", "діяльність", "The children were engaged in various activities at the park.", "Діти займалися різними видами діяльності в парку."],
    ["pine", "сосна", "The tall pine trees stood tall and proud.", "Високі сосни стояли високі і горді."],
    ["physical", "фізичний", "The physical therapist helped the patient regain their mobility."],
    ["engine", "двигун", "The engine of the car roared to life.", "Двигун автомобіля заревів."],
    ["ruin", "зруйнувати", "The war ruined the city.", "Війна зруйнувала місто."],
    ["harm", "зашкодити", "You should not harm animals.", "Не слід шкодити тваринам."],
    ["pet", "домашня тварина", "The dog is a popular pet.", "Собака - популярна домашня тварина."],
    ["circle", "коло", "The circle represents unity.", "Коло символізує єдність."],
    ["ducks", "качки", "The ducks swam gracefully in the pond.", "Качки граціозно плавали в ставку."],
    ["evasive", "ухильний", "The suspect was evasive when questioned by the police.", "Підозрюваний був ухильним під час допиту в поліції."],
    ["miniature", "мініатюрний", "The miniature dollhouse was a work of art.", "Мініатюрний ляльковий будиночок був твором мистецтва."],
    ["loud", "гучний", "The loud music woke me up in the middle of the night.", "Гучна музика розбудила мене серед ночі."],
    ["line", "лінія", "The line at the store was very long.", "Черга в магазині була дуже довгою."],
    ["curly", "кучерявий", "The girl had beautiful curly hair.", "У дівчини було гарне кучеряве волосся."],
    ["market", "ринок", "The farmer's market was full of fresh produce.", "Фермерський ринок був заповнений свіжими продуктами."],
    ["turkey", "індичка", "Turkey is a popular Thanksgiving dish.", "Індичка - популярна страва на День подяки."],
    ["identify", "визначати", "Я можу визначати об'єкти на зображенні.", "I can identify objects in an image."],
    ["right", "право", "Ти маєш право на свою думку.", "You have the right to your own opinion."],
    ["smoke", "дим", "Дим від вогню заповнив кімнату.", "The smoke from the fire filled the room."],
    ["wax", "віск", "Свічка зроблена з воску.", "The candle is made of wax."],
    ["shaky", "тремтливий", "У мене тремтять руки.", "My hands are shaking."],
    ["nerve", "нерв", "Треба мати міцні нерви, щоб бути лікарем.", "You need to have strong nerves to be a doctor."],
    ["spiteful", "злопам'ятний", "Він був злопам'ятний і ніколи не забував образи.", "He was spiteful and never forgot an insult."],
    ["ossified", "окостенілий", "Його думки були окостенілими і він не був відкритий для нових ідей.", "His thoughts were ossified and he was not open to new ideas."],
    ["neck", "шия", "У нього була довга і тонка шия.", "He had a long and thin neck."],
    ["grotesque", "гротескний", "Статуя була гротескною і моторошною.", "The statue was grotesque and scary."],
    ["striped", "смугастий", "Він був одягнений у смугасту футболку.", "He was wearing a striped T-shirt."],
    ["fuel", "паливо", "Бензин - це паливо, яке використовується в автомобілях.", "Gasoline is a fuel that is used in cars."],
    ["acceptable", "прийнятний", "Ця поведінка неприйнятна.", "This behavior is not acceptable."],
    ["attempt", "спроба", "Він зробив спробу полагодити машину, але не зміг.", "He made an attempt to fix the car, but he couldn't."],
    ["curl", "завиток", "У неї були красиві кучеряве локони.", "She had beautiful curly locks."],
    ["force", "сила", "Сила тяжіння притягує об'єкти до землі.", "Gravity pulls objects to the ground."],
    ["guide", "керівництво", "Туристичний гід показав нам місто.", "The tour guide showed us the city."],
    ["quarter", "чверть", "Чверть року пройшла дуже швидко.", "A quarter of the year went by very quickly."],
    ["glamorous", "гламурний", "Вона була гламурною зіркою кіно.", "She was a glamorous movie star."],
    ["crook", "шахрай", "Він був шахраєм і обдурював людей.", "He was a crook and cheated people."],
    ["connection", "зв'язок", "Він мав зв'язки у вищих колах.", "He had connections in high places."],
    ["traderace", "перегони на треку", "Він взяв участь у перегонах на треку.", "He took part in a track race."],
    ["salty", "солоний", "Суп був надто солоний.", "The soup was too salty."],
    ["stereotyped", "стереотипний", "Він був занадто стереотипним у своїх поглядах.", "He was too stereotypical in his views."],
    ["size", "розмір", "Він попросив мене вибрати розмір сорочки.", "He asked me to choose the size of the shirt."],
    ["repair", "ремонт", "Я віддав автомобіль в ремонт.", "I took the car for repair."],
    ["adjustment", "коректування", "Я зробив кілька коректувань у документі.", "I made a few adjustments to the document."],
    ["naughty", "неслухняний", "Дитина була неслухняною і не хотіла слухатись.", "The child was naughty and didn't want to listen."],
    ["sheet", "аркуш", "Я написав список на аркуші паперу.", "I wrote a list on a piece of paper."],
    ["fresh", "свіжий", "Я купив свіжі овочі.", "I bought fresh vegetables."],
    ["rest", "відпочинок", "Я потребував відпочинку після довгої подорожі.", "I needed a rest after a long journey."],
    ["homely", "домашній", "У нас є затишний і домашній будинок.", "We have a cozy and homely house."],
    ["happy", "щасливий", "I am happy today.", "Я сьогодні щасливий."],
    ["sad", "сумний", "I am sad that my friend is moving away.", "Мені сумно, що мій друг переїжджає."],
    ["angry", "злий", "I am angry that I missed my train.", "Я злий, що я запізнився на свій поїзд."],
    ["surprised", "здивований", "I was surprised to see my old friend at the party.", "Я був здивований, побачивши свого старого друга на вечірці."],
    ["scared", "наляканий", "I was scared when I heard the loud noise.", "Я налякався, коли почув гучний шум."],
    ["excited", "збуджений", "I am excited about our upcoming vacation.", "Я збуджений нашою майбутньою відпусткою."],
    ["bored", "занудьгував", "I was bored during the long lecture.", "Мені було нудно під час довгої лекції."],
    ["tired", "втомлений", "I am tired after a long day at work.", "Я втомлений після довгого робочого дня."],
    ["hungry", "голодний", "I am hungry for a pizza.", "Я голодний до піци."],
    ["thirsty", "спраглий", "I am thirsty for a glass of water.", "Мені хочеться випити склянку води."],
    ["vigorous", "енергійний", "The athlete ran a vigorous race.", "Спортсмен пробіг енергійні перегони."],
    ["suffer", "страждати", "The patient suffered from a chronic illness.", "Пацієнт страждав на хронічне захворювання."],
    ["watch", "дивитися", "I watched the movie last night.", "Я дивився фільм минулої ночі."],
    ["orange", "помаранчевий", "The orange tree was full of fruit.", "Помаранчеве дерево було повне плодів."],
    ["wanting", "бажаючи", "I am wanting a new car.", "Я хочу нову машину."],
    ["four", "чотири", "There are four people in the room.", "У кімнаті чотири людини."],
    ["wandering", "блукаючий", "The lost child wandered through the forest.", "Загублена дитина блукала лісом."],
    ["impulse", "імпульс", "I acted on impulse and bought the dress.", "Я діяв на імпульс і купив сукню."],
    ["soggy", "мокрий", "The cereal was soggy because I left it in the milk too long.", "Пластівці були мокрими, тому що я залишив їх у молоці занадто довго."],
    ["confuse", "збивати з пантелику", "The teacher's instructions confused the students.", "Вказівки вчителя збили студентів з пантелику."],
    ["sassy", "зухвалий", "The sassy child talked back to the teacher.", "Зухвала дитина відповіла вчительці."],
    ["tenuous", "тендітний", "The peace treaty was tenuous and could break down at any moment.", "Мирна угода була тендітною і могла будь-якої миті розвалитися."],
    ["brass", "латунь", "The band played a brass instrument.", "Гурт грав на латунному інструменті."],
    ["frogs", "жаби", "The frogs croaked in the pond.", "Жаби квакали в ставку."],
    ["wrist", "зап'ястя", "She broke her wrist when she fell off her bike.", "Вона зламала зап'ястя, коли впала з велосипеда."],
    ["smiling", "усміхаючись", "The girl smiled at me.", "Дівчина посміхнулася мені."],
    ["license", "ліцензія", "You need a license to drive a car.", "Вам потрібна ліцензія, щоб керувати автомобілем."],
    ["class", "клас", "I am in the same math class as you.", "Я в тому ж класі математики, що й ти."]
]

