vocab_list = [
    ["and", "та", "She likes coffee and tea.", "Вона любить каву та чай."],
    ["you", "ви", "I met you at the party.", "Я зустрів вас на вечірці."],
    ["they", "вони", "They went to the beach.", "Вони пішли на пляж."],
    ["or", "або", "Do you want tea or coffee?", "Ви хочете чай або каву?"],
    ["we", "ми", "We are going to the park.", "Ми йдемо в парк."],
    ["but", "але", "I like pizza, but I also enjoy pasta.", "Мені подобається піца, але я також люблю пасту."],
    ["she", "вона", "She is a doctor.", "Вона є лікарем."],
    ["so", "тому", "It was raining, so we stayed indoors.", "Ішов дощ, тому ми залишилися всередині."],
    ["there", "там", "I saw him there.", "Я бачив його там."],
    ["here", "тут, сюди", "Come here and sit down.", "Ходи сюди і сідай."],
    ["now", "зараз", "I'm busy right now.", "Зараз я зайнятий."],
    ["like", "подобатися", "I like ice cream.", "Мені подобається морозиво."],
    ["just", "просто", "I was just thinking about you.", "Я просто думав про тебе."],
    ["do", "робити", "What do you do for a living?", "Що ви робите для життя?"],
    ["can", "може", "Can you help me with this problem?", "Чи можете ви мені допомогти з цією проблемою?"],
    ["get", "отримати", "I need to get a new phone.", "Мені потрібно отримати новий телефон."],
    ["will", "буде", "It will rain tomorrow.", "Завтра буде дощ."],
    ["make", "робити", "She can make a delicious cake.", "Вона може зробити смачний торт."],
    ["see", "бачити", "I can't see without my glasses.", "Я не бачу без окулярів."],
    ["know", "знати", "Do you know the answer?", "Ти знаєш відповідь?"],
    ["come", "прийти", "Come to the party tonight.", "Прийди на вечірку сьогодні вечора."],
    ["think", "думати", "I think it's a good idea.", "Я думаю, це гарна ідея."],
    ["say", "говорити", "What did you say to him?", "Що ти сказав йому?"],
    ["see", "бачити", "I can see the mountains from here.", "Я бачу гори звідси."],
    ["take", "брати", "Can you take a photo for me?", "Чи можете ви зробити мені фото?"],
    ["help", "допомагати", "I need your help with this task.", "Мені потрібна твоя допомога з цим завданням."],
    ["use", "використовувати", "I use my laptop for work.", "Я використовую свій ноутбук для роботи."],
    ["find", "знаходити", "Can you help me find my keys?", "Чи можете ви мені допомогти знайти мої ключі?"],
    ["tell", "говорити, розповідати", "Can you tell me a story?", "Чи можете ви розповісти мені історію?"],
    ["ask", "питати", "Don't be afraid to ask questions.", "Не бійтеся питати питання."],
    ["work", "працювати", "I work from 9 to 5.", "Я працюю з 9 до 5."],
    ["seem", "здаватися", "It seems like a good idea.", "Здається, що це гарна ідея."],
    ["want", "хотіти", "I want to travel the world.", "Я хочу подорожувати по світу."],
    ["try", "спробувати", "I'll try my best to help you.", "Я спробую зробити все можливе, щоб вам допомогти."],
    ["need", "потребувати", "I need your advice.", "Мені потрібна ваша порада."],
    ["become", "стати", "I want to become a chef.", "Я хочу стати шеф-кухарем."],
    ["leave", "залишати", "Don't leave without saying goodbye.", "Не залишайтесь без прощання."],
    ["put", "класти", "Put the keys on the table.", "Покладіть ключі на стіл."],
    ["mean", "означати", "What does this word mean?", "Що означає це слово?"],
    ["keep", "тримати", "Can you keep a secret?", "Чи можете ви тримати секрет?"],
    ["start", "починати", "Let's start the meeting.", "Давайте почнемо нараду."],
    ["show", "показувати", "Can you show me the way?", "Чи можете ви мені показати дорогу?"],
    ["time", "час", "I don't have much time today.", "Сьогодні у мене не багато часу."],
    ["day", "день", "Tomorrow is a new day.", "Завтра новий день."],
    ["year", "рік", "I plan to travel next year.", "Я планую подорожувати наступного року."],
    ["way", "шлях", "Show me the way to the station.", "Покажіть мені шлях до вокзалу."],
    ["man", "чоловік", "The man is waiting for a bus.", "Чоловік чекає на автобус."],
    ["woman", "жінка", "She is a talented woman.", "Вона талановита жінка."],
    ["child", "дитина", "The child is playing in the park.", "Дитина грає в парку."],
    ["place", "місце", "Let's find a quiet place to talk.", "Знайдемо тихе місце для розмови."],
    ["thing", "річ", "I forgot to bring my things.", "Я забув взяти свої речі."],
    ["work", "робота", "I have a lot of work to do.", "У мене багато роботи."],
    ["job", "робота", "She got a new job.", "Вона отримала нову роботу."],
    ["house", "будинок", "I live in a small house.", "Я живу в невеликому будинку."],
    ["friend", "друг", "He is my best friend.", "Він мій найкращий друг."],
    ["family", "сім'я", "Family is important to me.", "Сім'я є важливою для мене."],
    ["life", "життя", "Enjoy every moment of life.", "Насолоджуйтеся кожним моментом життя."],
    ["school", "школа", "I go to school every day.", "Я ходжу до школи щодня."],
    ["book", "книга", "I love reading a good book.", "Я люблю читати хорошу книгу."],
    ["hand", "рука", "She extended her hand for a handshake.", "Вона простягла руку для рукостискання."],
    ["problem", "проблема", "We need to solve this problem.", "Нам потрібно вирішити цю проблему."],
    ["part", "частина", "I played a part in the school play.", "Я грав частину в шкільній виставі."],
    ["head", "голова", "I have a headache.", "У мене болить голова."],
    ["car", "автомобіль", "I drive a small car.", "Я керую маленьким автомобілем."],
    ["state", "штат", "California is a large state.", "Каліфорнія - це великий штат."],
    ["case", "випадок", "It's a unique case.", "Це унікальний випадок."],
    ["fact", "факт", "The fact is undeniable.", "Факт є неоспоримим."],
    ["example", "приклад", "Let me give you an example.", "Дозвольте мені подати вам приклад."],
    ["group", "група", "We are in the same group.", "Ми в одній групі."],
    ["change", "зміна", "Change is the only constant.", "Зміна - єдина постійна річ."],
    ["development", "розвиток", "Technological development is rapid.", "Технологічний розвиток є стрімким."],
    ["industry", "промисловість", "The city is known for its industry.", "Місто відоме своєю промисловістю."],
    ["system", "система", "A good education system is essential.", "Добра система освіти є важливою."],
    ["company", "компанія", "I work for a reputable company.", "Я працюю в поважній компанії."],
    ["number", "число", "The number of visitors is increasing.", "Число відвідувачів зростає."],
    ["government", "уряд", "The government is implementing new policies.", "Уряд впроваджує нові політики."],
    ["childhood", "дитинство", "Many memories are from my childhood.", "Багато спогадів з мого дитинства."],
    ["experience", "досвід", "Traveling provides valuable experience.", "Подорожі надають цінного досвіду."],
    ["community", "спільнота", "It's a close-knit community.", "Це згуртована спільнота."],
    ["area", "область", "This is a residential area.", "Це житлова область."],
    ["method", "метод", "Scientific methods are used in research.", "Наукові методи використовуються в дослідженнях."],
    ["point", "точка", "Let me explain my point of view.", "Дозвольте мені пояснити свою точку зору."],
    ["process", "процес", "Learning is a continuous process.", "Навчання - це постійний процес."],
    ["power", "сила", "Knowledge is a source of power.", "Знання - це джерело сили."]
]

