vocab_list = [
    ["the", "той, та, те, ті", "I like the book.", "Мені подобається та книга."],
    ["and", "і", "I went to the store and bought some apples.", "Я пішов у магазин і купив яблука."],
    ["you", "ти, ви", "I saw you yesterday.", "Я бачив тебе вчора."],
    ["a", "а, an", "I have a cat.", "У мене є кіт."],
    ["that", "той, та, те, ті", "I saw that movie.", "Я бачив той фільм."],
    ["is", "є", "The cat is on the mat.", "Кіт є на килимі."],
    ["of", "з, із, від", "The book is of great interest to me.", "Книга викликає у мене великий інтерес."],
    ["to", "до, на, в", "I went to the park.", "Я пішов до парку."],
    ["in", "у, в, на", "The cat is in the box.", "Кіт є в коробці."],
    ["this", "цей, ця, це, ці", "This is my book.", "Це моя книга."],
    ["have", "мати", "I have a pen.", "У мене є ручка."],
    ["it", "це, він, вона, воно", "I like it.", "Мені подобається це."],
    ["for", "за, для", "I bought this book for my friend.", "Я купив цю книгу для свого друга."],
    ["not", "не", "I do not like apples.", "Я не люблю яблука."],
    ["on", "на, у, на, в", "The book is on the table.", "Книга є на столі."],
    ["with", "з, із, з", "I went to the store with my friend.", "Я пішов у магазин з моїм другом."],
    ["he", "він", "He is my friend.", "Він є мій друг."],
    ["as", "як", "I like apples as much as oranges.", "Я люблю яблука так само сильно, як апельсини."],
    ["I", "я", "I am a student.", "Я є студент."],
    ["my", "мій, моя, моє, мої", "This is my book.", "Це моя книга."],
    ["are", "є", "The students are in the classroom.", "Студенти є в класі."],
    ["what", "що", "What is your name?", "Як тебе звати?"],
    ["be", "бути", "I will be there at 7 o'clock.", "Я буду там о 7 годині."],
]
